name: User Story
description: Create a new User Story following INVEST principles
title: "[US-XXX] "
labels: ["user-story", "enhancement"]
assignees: []
body:
  - type: input
    id: us_id
    attributes:
      label: User Story ID
      description: Unique identifier for this User Story (e.g., US-001, US-ABC-123)
      placeholder: "US-XXX"
    validations:
      required: true

  - type: textarea
    id: short_description
    attributes:
      label: Short Description
      description: Brief description following the "As a... I want... So that..." format
      placeholder: |
        **As a** [user type]
        **I want** [functionality]
        **So that** [business value/benefit]
      value: |
        **As a** 
        **I want** 
        **So that** 
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 🎯 Acceptance Criteria
      description: List the specific conditions that must be met for this story to be considered complete
      placeholder: |
        - [ ] Criterion 1: Description of what needs to be achieved
        - [ ] Criterion 2: Description of what needs to be achieved
        - [ ] Criterion 3: Description of what needs to be achieved
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 📝 Notes / Considerations
      description: Any additional notes, technical considerations, dependencies, or important information
      placeholder: |
        - Dependencies: List any dependencies on other stories or external systems
        - Technical notes: Any technical considerations or constraints
        - Design notes: UI/UX considerations if applicable
        - Risk considerations: Potential risks or challenges

  - type: checkboxes
    id: invest_checklist
    attributes:
      label: 📋 INVEST Checklist
      description: Verify this User Story follows INVEST principles
      options:
        - label: "**Independent**: This story can be developed and delivered independently of other stories"
          required: false
        - label: "**Negotiable**: The story details can be discussed and refined with stakeholders"
          required: false
        - label: "**Valuable**: This story provides clear value to users or the business"
          required: false
        - label: "**Estimable**: The story is clear enough to estimate effort required"
          required: false
        - label: "**Small**: The story is small enough to complete within a sprint/iteration"
          required: false
        - label: "**Testable**: The acceptance criteria are clear and testable"
          required: false

  - type: textarea
    id: invest_guide
    attributes:
      label: 💡 INVEST Guide
      description: Reference guide for INVEST principles (read-only for reference)
      value: |
        ## INVEST Principles for User Stories:
        
        - **Independent**: Stories should not depend on other stories and can be implemented in any order
        - **Negotiable**: Stories are not detailed contracts; they're starting points for conversation
        - **Valuable**: Each story must deliver value to users or stakeholders
        - **Estimable**: Stories should be clear enough for developers to estimate effort
        - **Small**: Stories should fit within a single iteration/sprint
        - **Testable**: Stories should have clear acceptance criteria that can be verified
        
        ### Tips:
        - Keep the story focused on user value, not technical implementation
        - Use acceptance criteria to define "done"
        - Break down large stories (epics) into smaller, manageable stories
        - Ensure each story can be demonstrated to stakeholders
      render: markdown
    validations:
      required: false