name: CI (Build + Test)

on:
  push:
    branches: ["main", "develop", "feature/*", "Feature/*"]
    paths:
      - "bot/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - "jest.config.cjs"
  pull_request:
    branches: ["main", "develop"]
    paths:
      - "bot/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
      - "jest.config.cjs"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configura Node 22 y pnpm (corepack)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Install deps
        run: |
          if [ -f package.json ] && [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; else echo "Sin package.json o pnpm-lock.yaml"; fi
      - name: Build
        run: |
          if [ -f package.json ]; then pnpm run build; fi
      - name: Run tests
        run: |
          if [ -f package.json ]; then pnpm -s run test --if-present; else echo "Sin tests"; fi

      # Paso opcional: build de la imagen (sin push en PR)
      - name: Set up QEMU
        if: github.event_name == 'push'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (no push) for PR validation
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          build-args: |
            GIT_SHA=${{ github.sha }}

      - name: Build & Push image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/rext-dev/setai-bot:${{ github.sha }}
            ghcr.io/rext-dev/setai-bot:latest
          build-args: |
            GIT_SHA=${{ github.sha }}
