name: CI (Build + Test + Docker)

on:
  push:
    branches: ["main", "develop", "feature/*"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm run test

      # Docker pasos solo si es push (no PR)
      - name: Set up QEMU
        if: github.event_name == 'push'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push imagen según rama
      - name: Build & Push Docker image (develop)
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/rext-dev/setai-bot:${{ github.sha }}
            ghcr.io/rext-dev/setai-bot:latest
            ghcr.io/rext-dev/setai-bot:develop
          build-args: |
            GIT_SHA=${{ github.sha }}

      - name: Build & Push Docker image (main)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/rext-dev/setai-bot:latest
            ghcr.io/rext-dev/setai-bot:stable
          build-args: |
            GIT_SHA=${{ github.sha }}

      # Build sin push para PR
      - name: Build Docker image (PR)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          build-args: |
            GIT_SHA=${{ github.sha }}
