name: Docker (Push sólo en main)

on:
  push:
    branches: ["main"]
    paths:
      - "bot/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "Dockerfile"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/rext-dev/setai-bot:${{ github.sha }}
            ghcr.io/rext-dev/setai-bot:latest
            ghcr.io/rext-dev/setai-bot:stable
          build-args: |
            GIT_SHA=${{ github.sha }}
